# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_405; end
module ::Anonymous_Delegator_406; end
module ::Anonymous_Delegator_409; end
